### ISSUE TITLE
A very large image will be blurry

### ISSUE THREAD

**Issue by LancerComet** [LancerComet/RuliaReader#29]
This is a known issue. I limited the rendering size of a single image to save memory, but in some conditions it would make it a bad reading experience, like when using vertical scrolling mode.

So I have two options:
 - Increase the rendering size
 - Split the image into multiple relatively small images in vertical scrolling mode

**Comment by LancerComet** [comment]
@ws123y

**Comment by ws123y** [comment]
2好像需要的代码会更多，容易出新问题
1的话感觉会不会对性能要求更高？这个可以试一下？

**Comment by LancerComet** [comment]
Add a switch to make users to decide whether the renderering size should be limited.

**Comment by LancerComet** [comment]
Toggle added @ws123y 

![image](https://github.com/LancerComet/RuliaReader/assets/10321350/d932234b-5d54-4601-aa7a-b105f7a08ca8)

**Comment by LancerComet** [comment]
Done
