### ISSUE TITLE
Sub folder access support.

### ISSUE THREAD

**Issue by northtowertop** [LancerComet/RuliaReader#37]
Currently RuliaReader can only list the files under main folder, all the sub folders and their contents will be ignored.
Is it possible to add sub folder support, so that we can move into the sub folder in the main folder view and see what's inside.
Many thanks.

目前为止RuliaReader貌似只能扫描主目录下的可阅读内容，而主文件夹下的所有子文件夹及其内容会被忽略。请问能不能增加对子文件夹的阅读支持呢，这样就能在主文件夹的视图下点击进入子文件夹，并查看其中的可阅读内容。十分感谢。

**Comment by LancerComet** [comment]
可以，不过可能要一段时间，最近比较忙

Cool, but it might take a while as I've been really busy recently

**Comment by LancerComet** [comment]
Done
